name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for main app Docker
        id: meta_app
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with: 
          images: cryseviel/github-actions-testing-node
          
      - name: Bulid and push main app Docker image
        id: push_app
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with: 
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta_app.outputs.tags }}
          labels: ${{ steps.meta_app.outputs.labels }}
          
      - name : Generate artifact attestation for Main App
        uses : actions/attest-build/provenance@v2
        with: 
          subject_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject_digest: ${{ steps.push_app.outputs.digest }}
          push-to-registry: true
          
      - name: Extract metadata (tags, labels) for main app Docker
        id: meta_nginx
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with: 
          images: cryseviel/github-actions-testing-node
          
      - name: Bulid and push nginx app Docker image
        id: push_nginx
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with: 
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ steps.meta_nginx.outputs.tags }}
          labels: ${{ steps.meta_nginx.outputs.labels }}
          
          
      - name : Generate artifact attestation for Nginx App
        uses : actions/attest-build/provenance@v2
        with: 
          subject_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject_digest: ${{ steps.push_nginx.outputs.digest }}
          push-to-registry: true
